fixed： 尝试本地安装bower解决网络无法访问 github问题

diff --git a/scripts/build/bigtop/patch1_0_4/child_patch/patch11-HADOOP-COMPILE-FAST.diff b/scripts/build/bigtop/patch1_0_4/child_patch/patch11-HADOOP-COMPILE-FAST.diff
--- a/scripts/build/bigtop/patch1_0_4/child_patch/patch11-HADOOP-COMPILE-FAST.diff
+++ b/scripts/build/bigtop/patch1_0_4/child_patch/patch11-HADOOP-COMPILE-FAST.diff
@@ -1,4 +1,4 @@
-Subject: [PATCH] fixed： 更换本地镜像源头
+Subject: [PATCH] fixed： 更换 镜像
 ---
 Index: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/bower.json
 IDEA additional info:
@@ -7,8 +7,8 @@ Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
 ===================================================================
 diff --git a/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/bower.json b/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/bower.json
 --- a/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/bower.json	(revision 2e576d7bdc858308f5a019534bbe77037deb1aa9)
-+++ b/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/bower.json	(date 1734597056761)
-@@ -1,29 +1,29 @@
++++ b/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/bower.json	(date 1734604059432)
+@@ -1,29 +1,33 @@
  {
    "name": "yarn-ui",
    "dependencies": {
@@ -60,6 +60,10 @@ diff --git a/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/src/main/webapp/bowe
 +    "alasql": "./bower_components/alasql",
 +    "x2js": "./bower_components/x2js",
 +    "qunit-notifications": "./bower_components/qunit-notifications"
++  },
++  "resolutions": {
++    "jquery": "1.9.1 - 3",
++    "moment": ">= 2.6.0"
    }
  }
 Index: hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/pom.xml
@@ -69,7 +73,7 @@ Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
 ===================================================================
 diff --git a/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/pom.xml b/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/pom.xml
 --- a/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/pom.xml	(revision 2e576d7bdc858308f5a019534bbe77037deb1aa9)
-+++ b/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/pom.xml	(date 1734597086615)
++++ b/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/pom.xml	(date 1734603928096)
 @@ -211,7 +211,7 @@
                  <phase>generate-resources</phase>
                  <id>bower install</id>
@@ -79,3 +83,51 @@ diff --git a/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/pom.xml b/hadoop-yar
                  </configuration>
                  <goals>
                    <goal>bower</goal>
+@@ -232,13 +232,43 @@
+                 <goals>
+                   <goal>exec</goal>
+                 </goals>
++<!--                <configuration>-->
++<!--                  <workingDirectory>${webappDir}</workingDirectory>-->
++<!--                  <executable>${nodeExecutable}</executable>-->
++<!--                  <arguments>-->
++<!--                    <argument>${packageManagerScript}</argument>-->
++<!--                    <argument>run</argument>-->
++<!--                    <argument>build:mvn</argument>-->
++<!--                  </arguments>-->
++<!--                </configuration>-->
+                 <configuration>
+                   <workingDirectory>${webappDir}</workingDirectory>
+-                  <executable>${nodeExecutable}</executable>
++                  <executable>bash</executable>
+                   <arguments>
+-                    <argument>${packageManagerScript}</argument>
+-                    <argument>run</argument>
+-                    <argument>build:mvn</argument>
++                    <argument>-c</argument>
++                    <argument>
++                      <![CDATA[
++                        max_retries=3
++                        count=0
++                        success=false
++
++                        while [[ $count -lt $max_retries ]]; do
++                          ${nodeExecutable} ${packageManagerScript} run build:mvn
++                          if [[ $? -eq 0 ]]; then
++                            success=true
++                            break
++                          fi
++                          count=$((count+1))
++                          echo "Retry $count/$max_retries..."
++                          sleep 2
++                        done
++
++                        if [[ "$success" == "false" ]]; then
++                          echo "Build failed after $max_retries attempts."
++                          exit 1
++                        fi
++                        ]]>
++                    </argument>
+                   </arguments>
+                 </configuration>
+               </execution>
